services:

  config-server:
    image: "rupesh1997/config-server:1.0.0"
    container_name: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configuration

  discovery-server:
    image: "rupesh1997/discovery-server:1.0.0"
    container_name: discovery-server
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-config-server-configuration
    environment:
      SPRING_APPLICATION_NAME: "discovery-server"

  product-db:
    container_name: product-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    extends:
      file: common-config.yml
      service: network-configuration

  product-service:
    image: "rupesh1997/product-service:1.0.0"
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
      product-db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "product-service"
    extends:
      file: common-config.yml
      service: microservice-discovery-server-configuration

  order-service:
    image: "rupesh1997/order-service:1.0.0"
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      discovery-server:
        condition: service_healthy
      product-db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "order-service"
    extends:
      file: common-config.yml
      service: microservice-discovery-server-configuration
#
#  cart-service:
#    image: "rupesh1997/cart-service:1.0.0"
#    container_name: cart-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      discovery-server:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: "cart-service"
#    extends:
#      file: common-config.yml
#      service: microservice-discovery-server-configuration
#
#  payment-service:
#    image: "rupesh1997/payment-service:1.0.0"
#    container_name: payment-service
#    ports:
#      - "8084:8084"
#    depends_on:
#      discovery-server:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: "payment-service"
#    extends:
#      file: common-config.yml
#      service: microservice-discovery-server-configuration

networks:
  purely-goods-nw:
    driver: "bridge"
volumes:
  mysql-data:

# docker compose -f docker/docker-compose/default/docker-compose.yml down
# docker compose -f docker/docker-compose/default/docker-compose.yml up -d
# docker logs <container-id>
# cat ~/.ssh/id_rsa