spring:
  config:
    activate:
      on-profile: "staging"

info:
  app:
    name: Order Service MS
    description: Handles order management, and filtering.
    version: 1.0.0
    owner: Rupesh Dulal
    website: https://www.alfarays.tech
    profile: 'staging'
  build:
    timestamp: "@timestamp@"
  developer:
    name: "Rupesh Dulal"
    email: "rupeshdulal672@gmail.com"
    github: "https://github.com/rupeshdulal"