info:
  app:
    name: Product Service MS
    description: Handles product management, images, categories, and filtering.
    version: 1.0.0
    owner: Rupesh Dulal
    website: https://www.alfarays.tech
    profile: production
  build:
    timestamp: "@timestamp@"
  developer:
    name: "Rupesh Dulal"
    email: "rupeshdulal672@gmail.com"
    github: "https://github.com/rupeshdulal"