name: DISCOVERY SERVER PIPELINE

on:
  push:
    branches:
      - main
    paths:
      - discovery-server/**
      - docker/backend/discovery-server/Dockerfile
      - docker/docker-compose/production/docker-compose.yaml
      - docker/docker-compose/production/common-config.yaml
      - .github/workflows/discovery-server-*.yaml

env:
  PROJECT_NAME: 'discovery-server'

jobs:
  setup:
    runs-on: self-hosted
    name: Setup Java environment and Checkout repository
    outputs:
      version: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Extract project version
        id: extract_version
        run: |
          cd ${{ env.PROJECT_NAME }}
          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=VERSION::${VERSION}"

  compile:
    runs-on: self-hosted
    name: Compile project
    needs: [ setup ]
    steps:
      - name: Compile project
        run: |
          cd ${{ env.PROJECT_NAME }}
          ./mvnw clean compile -DskipTests

  build:
    runs-on: self-hosted
    name: Build project
    needs: [ compile ]
    steps:
      - name: Build project
        run: |
          cd ${{ env.PROJECT_NAME }}
          ./mvnw clean package -DskipTests

  docker:
    runs-on: self-hosted
    name: Build and Push Docker Image
    needs: [ build ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET_KEY }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.PROJECT_NAME }}
          file: ./docker/backend/${{ env.PROJECT_NAME }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest
          build-args: |
            JAR_VERSION=${{ env.VERSION }}

  deployment:
    runs-on: self-hosted
    needs: [ docker ]
    name: Deployment
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment folder
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p deployment"

      - name: Copy Docker Compose and Config Files
        run: |
          scp docker/docker-compose/production/docker-compose.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yaml
          scp docker/docker-compose/production/common-config.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/common-config.yaml

      - name: Set Environment Variables and Deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd deployment
          docker system prune -f
          docker-compose -f docker-compose.yaml down
          docker-compose -f docker-compose.yaml pull -q
          docker-compose -f docker-compose.yaml up -d
          EOF
